version: 0.1.{build}
os: Visual Studio 2015
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- nuget restore
build:
  verbosity: minimal
test_script:
- ps: vstest.console /logger:Appveyor (Get-ChildItem -Recurse -Filter *.tests.dll | % {$_.FullName} | ? { $_ -like "*\bin\*"} ) /Platform:x64